"""initial migration

Revision ID: 21daeecd5111
Revises: 
Create Date: 2018-09-20 23:09:07.946736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21daeecd5111'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_info', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'case_info', 'project_info', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'case_info', type_='foreignkey')
    op.drop_column('case_info', 'project_id')
    # ### end Alembic commands ###
